name: SlimeGlue
version: '${version}'
main: com.xzavier0722.mc.plugin.slimeglue.SlimeGlue
api-version: '1.21'
depend: [ Slimefun ]
softdepend:
  - Kingdoms
  - Quickshop
  - QuickShop-Hikari
  - Magic
  - LockettePro
authors: [ Xzavier0722, wickidcow ]
description: Slimefun Legacy compatibility bridge for other Minecraft plugins
website: https://github.com/wickidcow/SF_SlimeGlue
